# Generated by Django 2.0 on 2018-08-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_auto_20180819_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='content',
            field=models.TextField(max_length=1000000),
        ),
    ]
