# Generated by Django 2.0 on 2018-08-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0003_auto_20180819_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paste',
            name='url',
            field=models.CharField(max_length=32),
        ),
    ]
