# Generated by Django 2.0 on 2018-08-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0005_remove_paste_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='url',
            field=models.CharField(default='sdf', max_length=32),
            preserve_default=False,
        ),
    ]
