# Generated by Django 2.0 on 2018-08-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0007_auto_20180819_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='url',
            field=models.AutoField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
