# Generated by Django 2.0 on 2018-08-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0010_paste_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='owner',
        ),
    ]
