# Generated by Django 2.0 on 2018-08-21 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastebin', '0011_remove_paste_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='paste_logged_in',
            fields=[
                ('content', models.TextField(max_length=1000000)),
                ('url', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
