# Generated by Django 2.0 on 2018-08-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0012_paste_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste_logged_in',
            name='owner',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
