# Generated by Django 2.0 on 2018-08-24 09:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0013_auto_20180822_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='content',
            field=tinymce.models.HTMLField(max_length=1000000),
        ),
    ]
