# Generated by Django 2.0 on 2018-08-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0014_auto_20180824_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='content',
            field=models.TextField(max_length=1000000),
        ),
    ]
