# Generated by Django 2.0 on 2018-08-25 12:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0015_auto_20180825_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=1000000),
        ),
    ]
