# Generated by Django 2.0 on 2018-08-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0016_auto_20180825_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
