# Generated by Django 2.0 on 2018-08-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0017_paste_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste_logged_in',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
