# Generated by Django 2.0 on 2018-08-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0018_paste_logged_in_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
