# Generated by Django 2.0 on 2018-08-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0019_paste_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste_logged_in',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
